foreground              #FFFFFF
background              #05172D
selection_foreground    #05172D
selection_background    #FFFFFF
cursor                  #45BBE0
cursor_text_color       #131110

active_tab_foreground     #05172D
active_tab_background     #094384
inactive_tab_foreground   #094384
inactive_tab_background   #05172D

# black
color0      #293B52
color8      #57708F

# red
color1      #CCF3FF
color9      #AADFF0

# green
color2      #CCEDFF
color10     #AAD7F0

# yellow
color3      #CCE4FF
color11     #AACBF0

# blue
color4      #9ABCE6
color12     #9ABCE6

# magenta
color5      #9ACBE6
color13     #9ACBE6

# cyan
color6      #9ABDE6
color14     #9ABDE6

# white
color7      #CCF3FF
color15     #AADFF0
