foreground              #FFFFFF
background              #050734
selection_foreground    #050734
selection_background    #FFFFFF
cursor                  #8F1AC3
cursor_text_color       #FFFFFF

active_tab_foreground     #050734
active_tab_background     #3AD3F2
inactive_tab_foreground   #3AD3F2
inactive_tab_background   #050734

# black
color0      #292B52
color8      #57598F

# red
color1      #EFCCFF
color9      #DAAAF0

# green
color2      #CCD4FF
color10     #AAB6F0

# yellow
color3      #CCF6FF
color11     #AAE4F0

# blue
color4      #9A9DE6
color12     #9A9DE6

# magenta
color5      #9AA6E6
color13     #9AA6E6

# cyan
color6      #9AD9E6
color14     #9AD9E6

# white
color7      #EFCCFF
color15     #DAAAF0
