foreground              #FFFFFF
background              #101D33
selection_foreground    #101D33
selection_background    #FFFFFF
cursor                  #9FD9E4
cursor_text_color       #0A0909

active_tab_foreground     #101D33
active_tab_background     #4D94AA
inactive_tab_foreground   #4D94AA
inactive_tab_background   #101D33

# black
color0      #293852
color8      #576C8F

# red
color1      #CCF7FF
color9      #AAE5F0

# green
color2      #CCEBFF
color10     #AAD4F0

# yellow
color3      #CCF3FF
color11     #AADFF0

# blue
color4      #9AB6E6
color12     #9AB6E6

# magenta
color5      #9AC7E6
color13     #9AC7E6

# cyan
color6      #9AD4E6
color14     #9AD4E6

# white
color7      #CCF7FF
color15     #AAE5F0
