-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀

--# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

-- mira https://wiki.hypr.land/configuring/keywords/ para más información

-- para ver ejemplos de atajos, mira https://wiki.hypr.land/configuring/binds/

--? ------- COMPATIBLE CON KEYBINDS_HYPRLAND_V_0_53 ----------------

--   Esta configuración es compatible con los cambios de atajos en Hyprland v0.53+

--   Para asegurar que tu sistema funcione, no deshabilitaremos este bloque

--   Los archivos de plantilla del usuario se proporcionarán en $XDG_DATA_HOME/hyde/templates/hypr/keybindings.conf para actualización manual.

--? ------- Agrupación de atajos para una gestión más fácil ----------------

--  $d=[Nombre del Grupo|Nombre del Subgrupo1|Nombre del Subgrupo2|...]

-- '$d' es una variable que se utiliza para agrupar atajos (o usar otra variable)

-- Esto es solo para fines de organización y no es una variable definida por hyprland

-- Lo que hicimos aquí fue modificar la Descripción de los atajos para incluir el nombre del grupo

-- El $d será analizado como una clave separada para usarse en una GUI (interfaz gráfica) o algo visual

-- [Principal|Subgrupo1|Subgrupo2|...]

-- Principal - El nombre del grupo principal

-- Subgrupo1.. - Los nombres de los subgrupos se pueden usar para evitar repetir la misma descripción

--? ------- Variables ----------------

-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"
local BROWSER = "firefox"
local DISCORD = "flatpak run io.github.spacingbat3.webcord"
local terminal = "kitty"
local fileManager = "dolphin"
local editor= "code"

local wm = "Window Management"
local d = "[Window Management]"

-- Cierra la ventana que tienes actualmente enfocada.
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("$KILLACTIVE"))

-- Atajo alternativo (clásico de Windows) para cerrar la ventana enfocada.
hl.bind("ALT + F4", hl.dsp.exec_cmd("$KILLACTIVE"))

-- Cierra tu sesión actual de Hyprland (regresa al login).
hl.bind(mainMod .. " + SHIFT + Delete", hl.dsp.exec_cmd("hyde-shell logout"))

-- Cambia la ventana enfocada entre el modo "flotante" y el modo "mosaico" (tiling).
hl.bind(mainMod .. " + W", hl.dsp.window.float())

-- Agrupa o desagrupa ventanas para manejarlas por pestañas (tabbed).
hl.bind(mainMod .. " + G", hl.dsp.group.toggle())

-- Pone la ventana enfocada en modo pantalla completa.
hl.bind("SHIFT + F11", hl.dsp.window.fullscreen())

-- Bloquea la pantalla de tu computadora.
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyde-shell lock-session"))

-- Fija (hace "pin") una ventana flotante para que sea visible en todos los espacios de trabajo.
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("hyde-shell window.pin"))

-- Muestra el menú gráfico de apagado, reinicio y cierre de sesión.
hl.bind(mainMod .. " + Delete", hl.dsp.exec_cmd("hyde-shell logoutlaunch"))

-- Oculta temporalmente la barra superior (Waybar) y recarga su configuración.
hl.bind("Alt_R + Control_R", hl.dsp.exec_cmd("hyde-shell waybar --hide"))

local d = "[Window Management|Group Navigation]"
hl.bind(mainMod .. " + CONTROL + H", hl.dsp.group.next({ forward = false }))
hl.bind(mainMod .. " + CONTROL + L", hl.dsp.group.next())

local d = "[Window Management|Change focus]"
hl.bind(mainMod .. " + Left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + Right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + Up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + Down", hl.dsp.focus({ direction = "down" }))
hl.bind("ALT + Tab", hl.dsp.exec_cmd("hyprctl --batch \"dispatch cyclenext ; dispatch alterzorder top\""))

local d = "[Window Management|Resize Active Window]"
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 30 0"))
hl.bind(mainMod .. " + SHIFT + Left", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -30 0"))
hl.bind(mainMod .. " + SHIFT + Up", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -30"))
hl.bind(mainMod .. " + SHIFT + Down", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 30"))

local d = "[Window Management|Move active window across workspace]"
local moveactivewindow = "grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive"
hl.bind(mainMod .. " + SHIFT + CONTROL + left", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive -30 0 || hyprctl dispatch movewindow l"))
hl.bind(mainMod .. " + SHIFT + CONTROL + right", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 30 0 || hyprctl dispatch movewindow r"))
hl.bind(mainMod .. " + SHIFT + CONTROL + up", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 -30 || hyprctl dispatch movewindow u"))
hl.bind(mainMod .. " + SHIFT + CONTROL + down", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 30 || hyprctl dispatch movewindow d"))

local d = "[Window Management|Move & Resize with mouse]"
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(mainMod .. " + Z", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + X", hl.dsp.window.resize(), { mouse = true })

local d = "[Window Management]"
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

local l = "Launcher"
local d = "[Launcher|Apps]"
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + ALT + T", hl.dsp.exec_cmd("hyde-shell pypr toggle console"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(editor))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(BROWSER))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("firefox --private-window"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"webcord\" ; then hyprctl dispatch killactive \"\" ; else flatpak run io.github.spacingbat3.webcord; fi'"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("flatpak kill io.github.spacingbat3.webcord"))
hl.bind(mainMod .. " + CONTROL_L + S", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"steam\" ; then hyprctl dispatch killactive \"\" ; else steam; fi'"))
hl.bind(mainMod .. " + SHIFT + CONTROL_L + S", hl.dsp.exec_cmd("pkill -9 -f steam"))
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("hyde-shell system.monitor"))
hl.bind(mainMod .. " + ALT + Escape", hl.dsp.exec_cmd("terminal -e btop"))
hl.bind(mainMod .. " + SHIFT + Escape", hl.dsp.exec_cmd("terminal -e nvtop"))

local d = "[Launcher|Rofi menus]"
local rofi_launch = "hyde-shell rofilaunch"
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || " .. rofi_launch .. " d'"))
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || " .. rofi_launch .. " w'"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || " .. rofi_launch .. " f'"))
hl.bind(mainMod .. " + minus", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell keybinds_hint c'"))
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell emoji-picker'"))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell glyph-picker'"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell cliphist -c'"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell cliphist'"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell rofiselect'"))

local hc = "Hardware Controls"
local d = "[Hardware Controls|Audio]"
hl.bind("F10", hl.dsp.exec_cmd("hyde-shell volumecontrol -o m"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("hyde-shell volumecontrol -o m"), { locked = true })
hl.bind("F11", hl.dsp.exec_cmd("hyde-shell volumecontrol -o d"), { locked = true })
hl.bind("F12", hl.dsp.exec_cmd("hyde-shell volumecontrol -o i"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("hyde-shell volumecontrol -i m"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("hyde-shell volumecontrol -o d"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("hyde-shell volumecontrol -o i"), { locked = true })

local d = "[Hardware Controls|Media]"
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(mainMod .. " + CONTROL + M", hl.dsp.exec_cmd("hyde-shell window.mute"))

local d = "[Hardware Controls|Brightness]"
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("hyde-shell brightnesscontrol i"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("hyde-shell brightnesscontrol d"), { locked = true })

local ut = "Utilities"
local d = "[Utilities]"
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("hyde-shell keyboardswitch"), { locked = true })
hl.bind(mainMod .. " + ALT + G", hl.dsp.exec_cmd("hyde-shell gamemode"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("hyde-shell gamelauncher"))

local d = "[Utilities|Screen Capture]"
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -an"))
hl.bind(mainMod .. " + CONTROL + P", hl.dsp.exec_cmd("hyde-shell screenshot s"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("sh -c 'ARCHIVO=\"/tmp/Captura_$(date +%H-%M-%S).png\" ; grim -g \"$(slurp)\" \"$ARCHIVO\" && echo -n \"file://$ARCHIVO\"| wl-copy -t text/uri-list'"))
hl.bind(mainMod .. " + ALT + P", hl.dsp.exec_cmd("hyde-shell screenshot m"), { locked = true })
hl.bind("Print", hl.dsp.exec_cmd("hyde-shell screenshot p"), { locked = true })

local rice = "Theming and Wallpaper"
local d = "[Theming and Wallpaper]"
hl.bind(mainMod .. " + ALT + Right", hl.dsp.exec_cmd("hyde-shell wallpaper -Gn"))
hl.bind(mainMod .. " + ALT + Left", hl.dsp.exec_cmd("hyde-shell wallpaper -Gp"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell wallpaper -SG"))
hl.bind(mainMod .. " + ALT + Up", hl.dsp.exec_cmd("hyde-shell wbarconfgen n"))
hl.bind(mainMod .. " + ALT + Down", hl.dsp.exec_cmd("hyde-shell wbarconfgen p"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell wallbashtoggle -m"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell themeselect"))
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell animations --select"))
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell hyprlock --select"))

local ws = "Workspaces"
local d = "[Workspaces|Navigation]"
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }))
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

local d = "[Workspaces|Navigation|Relative workspace]"
hl.bind(mainMod .. " + CONTROL + Right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mainMod .. " + CONTROL + Left", hl.dsp.focus({ workspace = "r-1" }))

local d = "[Workspaces|Navigation]"
hl.bind(mainMod .. " + CONTROL + Down", hl.dsp.focus({ workspace = "empty" }))

local d = "[Workspaces|Move window to workspace]"
for i = 1, 9 do
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

local d = "[Workspaces]"
hl.bind(mainMod .. " + CONTROL + ALT + Right", hl.dsp.exec_cmd("hyprctl dispatch movetoworkspace r+1"))
hl.bind(mainMod .. " + CONTROL + ALT + Left", hl.dsp.exec_cmd("hyprctl dispatch movetoworkspace r-1"))

local d = "[Workspaces|Navigation]"
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

local d = "[Workspaces|Navigation|Special workspace]"
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special" }, { follow = false }))
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special(nil))

local d = "[Workspaces|Navigation|Move window silently]"
for i = 1, 9 do
    hl.bind(mainMod .. " + ALT + " .. i, hl.dsp.window.move({ workspace = i }, { follow = false }))
end
hl.bind(mainMod .. " + ALT + 0", hl.dsp.window.move({ workspace = 10 }, { follow = false }))