-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local HYDE_HYPRLAND = "set"

--! Do not remove - HyDE marker to prevent file overwrite

--* You can freely edit this file, but make sure to not remove the above line!

--* All Files Below are yours to modify!
--!      ░▒▒▒░░░▓▓           ___________
--!    ░░▒▒▒░░░░░▓▓        //___________/
--!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
--!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
--!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
--!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
--!       ░▒▓▓   ▓▓  //____/

-- ------------------------------------------------------

--TODO Please remove this block if you are sure $HYPRLAND_CONFIG is set

--? This is only use for fallback

-- source = $HOME/.local/share/hyde/hyprland.conf -> requires manual conversion
-- local hyprland = require("_local.share.hyde.hyprland")
-- TODO: convert $HOME/.local/share/hyde/hyprland.conf to .lua and use require()

-- Fallback when HYPRLAND_CONFIG is not set

-- -------------------------------------------------------

--? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

-- ==============================================================================
-- CARGADOR AUTOMÁTICO DE MÓDULOS .LUA
-- ==============================================================================

local config_dir = debug.getinfo(1, "S").source:match("@?(.*/)") or "./"

-- Lee la carpeta actual y busca todos los archivos que terminen en .lua
local pfile = io.popen('find "' .. config_dir .. '" -maxdepth 1 -name "*.lua" -not -name "hyprland.lua"')

if pfile then
    for filename in pfile:lines() do
        -- Extrae solo el nombre del archivo sin la ruta ni la extensión
        local modname = filename:match("^.*/([^/]+)%$") or filename:match("^(.-)%.lua$")
        -- Limpia la extensión .lua si quedó atrapada
        modname = modname:gsub("%.lua$", "")
        
        -- Carga el módulo de manera segura
        if modname ~= "" then
            pcall(require, modname)
        end
    end
    pfile:close()
end

-- Your hyprland configuration // Edit this file to change your Hyprland configuration

hl.config({
    input = {
        kb_layout = "latam",
    },
})



