-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua

---@module 'hl'

local mainMod = "SUPER"
local BROWSER = "firefox"
local DISCORD = "flatpak run io.github.spacingbat3.webcord"
local terminal = "kitty"
local fileManager = "dolphin"
local editor = "code"

local wm = "Window Management"
local d = "[Window Management]"

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("$KILLACTIVE"), { description = d .. " cerrar ventana enfocada" })
hl.bind("ALT + F4", hl.dsp.exec_cmd("$KILLACTIVE"), { description = d .. " cerrar ventana enfocada" })
hl.bind(mainMod .. " + SHIFT + Delete", hl.dsp.exec_cmd("hyde-shell logout"), { description = d .. " cerrar sesion hyprland" })
hl.bind(mainMod .. " + W", hl.dsp.window.float(), { description = d .. " alternar modo flotante" })
hl.bind(mainMod .. " + G", hl.dsp.group.toggle(), { description = d .. " alternar grupo" })
hl.bind("SHIFT + F11", hl.dsp.window.fullscreen(), { description = d .. " alternar pantalla completa" })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyde-shell lock-session"), { description = d .. " bloquear pantalla" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("hyde-shell window.pin"), { description = d .. " fijar ventana enfocada" })
hl.bind(mainMod .. " + Delete", hl.dsp.exec_cmd("hyde-shell logoutlaunch"), { description = d .. " menu de apagado" })
hl.bind("Alt_R + Control_R", hl.dsp.exec_cmd("hyde-shell waybar --hide"), { description = d .. " alternar y recargar waybar" })

local d = "[Window Management|Group Navigation]"
hl.bind(mainMod .. " + CONTROL + H", hl.dsp.group.next({ forward = false }), { description = d .. " grupo activo anterior" })
hl.bind(mainMod .. " + CONTROL + L", hl.dsp.group.next(), { description = d .. " grupo activo siguiente" })

local d = "[Window Management|Change focus]"
hl.bind(mainMod .. " + Left", hl.dsp.focus({ direction = "left" }), { description = d .. " enfocar izquierda" })
hl.bind(mainMod .. " + Right", hl.dsp.focus({ direction = "right" }), { description = d .. " enfocar derecha" })
hl.bind(mainMod .. " + Up", hl.dsp.focus({ direction = "up" }), { description = d .. " enfocar arriba" })
hl.bind(mainMod .. " + Down", hl.dsp.focus({ direction = "down" }), { description = d .. " enfocar abajo" })
hl.bind("ALT + Tab", hl.dsp.exec_cmd("hyprctl --batch \"dispatch cyclenext ; dispatch alterzorder top\""), { description = d .. " ciclar enfoque" })

local d = "[Window Management|Resize Active Window]"
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 30 0"), { description = d .. " redimensionar ventana derecha" })
hl.bind(mainMod .. " + SHIFT + Left", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -30 0"), { description = d .. " redimensionar ventana izquierda" })
hl.bind(mainMod .. " + SHIFT + Up", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -30"), { description = d .. " redimensionar ventana arriba" })
hl.bind(mainMod .. " + SHIFT + Down", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 30"), { description = d .. " redimensionar ventana abajo" })

local d = "[Window Management|Move active window across workspace]"
local moveactivewindow = "grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive"
hl.bind(mainMod .. " + SHIFT + CONTROL + left", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive -30 0 || hyprctl dispatch movewindow l"), { description = d .. " mover ventana activa izquierda" })
hl.bind(mainMod .. " + SHIFT + CONTROL + right", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 30 0 || hyprctl dispatch movewindow r"), { description = d .. " mover ventana activa derecha" })
hl.bind(mainMod .. " + SHIFT + CONTROL + up", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 -30 || hyprctl dispatch movewindow u"), { description = d .. " mover ventana activa arriba" })
hl.bind(mainMod .. " + SHIFT + CONTROL + down", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 30 || hyprctl dispatch movewindow d"), { description = d .. " mover ventana activa abajo" })

local d = "[Window Management|Move & Resize with mouse]"
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true, description = d .. " mantener para mover ventana" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true, description = d .. " mantener para redimensionar ventana" })
hl.bind(mainMod .. " + Z", hl.dsp.window.drag(), { mouse = true, description = d .. " mantener para mover ventana" })
hl.bind(mainMod .. " + X", hl.dsp.window.resize(), { mouse = true, description = d .. " mantener para redimensionar ventana" })

local d = "[Window Management]"
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), { description = d .. " alternar division" })

local l = "Launcher"
local d = "[Launcher|Apps]"
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal), { description = d .. " emulador de terminal" })
hl.bind(mainMod .. " + ALT + T", hl.dsp.exec_cmd("hyde-shell pypr toggle console"), { description = d .. " terminal desplegable" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), { description = d .. " explorador de archivos" })
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(editor), { description = d .. " editor de texto" })
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(BROWSER), { description = d .. " navegador web" })
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("firefox --private-window"), { description = d .. " navegador web incognito" })
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"webcord\" ; then hyprctl dispatch killactive \"\" ; else flatpak run io.github.spacingbat3.webcord; fi'"), { description = d .. " discord" })
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("flatpak kill io.github.spacingbat3.webcord"), { description = d .. " cerrar discord" })
hl.bind(mainMod .. " + CONTROL_L + S", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"steam\" ; then hyprctl dispatch killactive \"\" ; else steam; fi'"), { description = d .. " steam" })
hl.bind(mainMod .. " + SHIFT + CONTROL_L + S", hl.dsp.exec_cmd("pkill -9 -f steam"), { description = d .. " cerrar steam" })
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("hyde-shell system.monitor"), { description = d .. " monitor del sistema" })
hl.bind(mainMod .. " + ALT + Escape", hl.dsp.exec_cmd("terminal -e btop"), { description = d .. " abrir btop" })
hl.bind(mainMod .. " + SHIFT + Escape", hl.dsp.exec_cmd("terminal -e nvtop"), { description = d .. " abrir nvtop" })

local d = "[Launcher|Rofi menus]"
local rofi_launch = "hyde-shell rofilaunch"
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || " .. rofi_launch .. " d'"), { description = d .. " buscador de aplicaciones" })
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || " .. rofi_launch .. " w'"), { description = d .. " intercambiador de ventanas" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || " .. rofi_launch .. " f'"), { description = d .. " buscador de archivos" })
hl.bind(mainMod .. " + minus", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell keybinds_hint c'"), { description = d .. " pista de atajos" })
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell emoji-picker'"), { description = d .. " selector de emojis" })
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell glyph-picker'"), { description = d .. " selector de glifos" })
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell cliphist -c'"), { description = d .. " portapapeles" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell cliphist'"), { description = d .. " administrador del portapapeles" })
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("sh -ic 'pkill -x rofi || hyde-shell rofiselect'"), { description = d .. " seleccionar lanzador rofi" })

local hc = "Hardware Controls"
local d = "[Hardware Controls|Audio]"
hl.bind("F10", hl.dsp.exec_cmd("hyde-shell volumecontrol -o m"), { locked = true, description = d .. " alternar silencio de salida" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("hyde-shell volumecontrol -o m"), { locked = true, description = d .. " alternar silencio de salida" })
hl.bind("F11", hl.dsp.exec_cmd("hyde-shell volumecontrol -o d"), { locked = true, description = d .. " bajar volumen" })
hl.bind("F12", hl.dsp.exec_cmd("hyde-shell volumecontrol -o i"), { locked = true, description = d .. " subir volumen" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("hyde-shell volumecontrol -i m"), { locked = true, description = d .. " alternar silencio de microfono" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("hyde-shell volumecontrol -o d"), { locked = true, description = d .. " bajar volumen" })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("hyde-shell volumecontrol -o i"), { locked = true, description = d .. " subir volumen" })

local d = "[Hardware Controls|Media]"
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = d .. " reproducir o pausar multimedia" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = d .. " pausar multimedia" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = d .. " multimedia siguiente" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = d .. " multimedia anterior" })
hl.bind(mainMod .. " + CONTROL + M", hl.dsp.exec_cmd("hyde-shell window.mute"), { description = d .. " alternar silencio en ventana activa" })

local d = "[Hardware Controls|Brightness]"
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("hyde-shell brightnesscontrol i"), { locked = true, description = d .. " subir brillo" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("hyde-shell brightnesscontrol d"), { locked = true, description = d .. " bajar brillo" })

local ut = "Utilities"
local d = "[Utilities]"
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("hyde-shell keyboardswitch"), { locked = true, description = d .. " cambiar distribucion de teclado" })
hl.bind(mainMod .. " + ALT + G", hl.dsp.exec_cmd("hyde-shell gamemode"), { description = d .. " modo juego" })
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("hyde-shell gamelauncher"), { description = d .. " abrir lanzador de juegos" })

local d = "[Utilities|Screen Capture]"
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -an"), { description = d .. " selector de color" })
hl.bind(mainMod .. " + CONTROL + P", hl.dsp.exec_cmd("hyde-shell screenshot s"), { description = d .. " recortar pantalla" })
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("sh -c 'ARCHIVO=\"/tmp/Captura_$(date +%H-%M-%S).png\" ; grim -g \"$(slurp)\" \"$ARCHIVO\" && echo -n \"file://$ARCHIVO\"| wl-copy -t text/uri-list'"), { description = d .. " recortar pantalla" })
hl.bind(mainMod .. " + ALT + P", hl.dsp.exec_cmd("hyde-shell screenshot m"), { locked = true, description = d .. " capturar monitor" })
hl.bind("Print", hl.dsp.exec_cmd("hyde-shell screenshot p"), { locked = true, description = d .. " capturar todos los monitores" })

local rice = "Theming and Wallpaper"
local d = "[Theming and Wallpaper]"
hl.bind(mainMod .. " + ALT + Right", hl.dsp.exec_cmd("hyde-shell wallpaper -Gn"), { description = d .. " siguiente fondo global" })
hl.bind(mainMod .. " + ALT + Left", hl.dsp.exec_cmd("hyde-shell wallpaper -Gp"), { description = d .. " anterior fondo global" })
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell wallpaper -SG"), { description = d .. " seleccionar fondo global" })
hl.bind(mainMod .. " + ALT + Up", hl.dsp.exec_cmd("hyde-shell wbarconfgen n"), { description = d .. " siguiente diseño waybar" })
hl.bind(mainMod .. " + ALT + Down", hl.dsp.exec_cmd("hyde-shell wbarconfgen p"), { description = d .. " anterior diseño waybar" })
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell wallbashtoggle -m"), { description = d .. " selector de modo wallbash" })
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell themeselect"), { description = d .. " seleccionar tema" })
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell animations --select"), { description = d .. " seleccionar animaciones" })
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell hyprlock --select"), { description = d .. " seleccionar diseño hyprlock" })

local ws = "Workspaces"
local d = "[Workspaces|Navigation]"
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }), { description = d .. " navegar al espacio " .. i })
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }), { description = d .. " navegar al espacio 10" })

local d = "[Workspaces|Navigation|Relative workspace]"
hl.bind(mainMod .. " + CONTROL + Right", hl.dsp.focus({ workspace = "r+1" }), { description = d .. " espacio activo siguiente" })
hl.bind(mainMod .. " + CONTROL + Left", hl.dsp.focus({ workspace = "r-1" }), { description = d .. " espacio activo anterior" })

local d = "[Workspaces|Navigation]"
hl.bind(mainMod .. " + CONTROL + Down", hl.dsp.focus({ workspace = "empty" }), { description = d .. " navegar al espacio vacio mas cercano" })

local d = "[Workspaces|Move window to workspace]"
for i = 1, 9 do
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }), { description = d .. " mover al espacio " .. i })
end
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }), { description = d .. " mover al espacio 10" })

local d = "[Workspaces]"
hl.bind(mainMod .. " + CONTROL + ALT + Right", hl.dsp.exec_cmd("hyprctl dispatch movetoworkspace r+1"), { description = d .. " mover ventana al espacio relativo siguiente" })
hl.bind(mainMod .. " + CONTROL + ALT + Left", hl.dsp.exec_cmd("hyprctl dispatch movetoworkspace r-1"), { description = d .. " mover ventana al espacio relativo anterior" })

local d = "[Workspaces|Navigation]"
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = d .. " espacio siguiente" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = d .. " espacio anterior" })

local d = "[Workspaces|Navigation|Special workspace]"
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special" }), { description = d .. " mover al scratchpad" })
hl.bind(mainMod .. " + ALT + S", hl.dsp.window.move({ workspace = "special" }, { follow = false }), { description = d .. " mover al scratchpad (silencioso)" })
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special(nil), { description = d .. " alternar scratchpad" })

local d = "[Workspaces|Navigation|Move window silently]"
for i = 1, 9 do
    hl.bind(mainMod .. " + ALT + " .. i, hl.dsp.window.move({ workspace = i }, { follow = false }), { description = d .. " mover al espacio " .. i .. " (silencioso)" })
end
hl.bind(mainMod .. " + ALT + 0", hl.dsp.window.move({ workspace = 10 }, { follow = false }), { description = d .. " mover al espacio 10 (silencioso)" })