-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--! █▀ █░█ ▄▀█ █▀▄ █▀▀ █▀█ █▀

--! ▄█ █▀█ █▀█ █▄▀ ██▄ █▀▄ ▄█

-- *┌────────────────────────────────────────────────────────────────────────────┐

-- *│                                                                            |

-- *│ HyDE Controlled content DO NOT EDIT!                                      |

-- *│ Edit or add shaders in the ./shaders/ directory                           |

-- *│ and run the 'shaders.sh --select' command to update this file             |

-- *│ Modify ./shaders/shader-name.inc to add your own custom defines         |

-- *│ The 'shader.sh' script will automatically copy this file to the cache     |

-- *│ and the cache will be used in the shader                                  |

-- *│                                                                            |

-- *└────────────────────────────────────────────────────────────────────────────┘

-- name of the shader

local SCREEN_SHADER = "disable"

-- path to the shader

local SCREEN_SHADER_PATH = "local_var_XDG_CONFIG_HOME/hypr/shaders/disable.frag"

-- path to the compiled shader // override this in '../hyde/config.toml'

local SCREEN_SHADER_COMPILED = "local_var_XDG_CONFIG_HOME/hypr/shaders/.compiled.cache.glsl"
