-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--! ▄▀█ █▄░█ █ █▀▄▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█

--! █▀█ █░▀█ █ █░▀░█ █▀█ ░█░ █ █▄█ █░▀█

-- See https://wiki.hypr.land/Configuring/Animations/

-- HyDE Controlled content // DO NOT EDIT

-- Edit or add animations in the ./hypr/animations/ directory

-- and run the 'animations.sh --select' command to update this file

local ANIMATION = "theme"

local ANIMATION_PATH = "./animations/theme.conf"

-- source = $ANIMATION_PATH -> requires manual conversion
-- local _ANIMATION_PATH = require("_ANIMATION_PATH")
-- TODO: convert $ANIMATION_PATH to .lua and use require()
