-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua

---@module 'hl'

-- Habilitar deduplicación de atajos (función del nuevo HyDE)
hyde.binds.dedup = true

local mainMod = "SUPER"
local BROWSER = "firefox"
local DISCORD = "flatpak run io.github.spacingbat3.webcord"
local terminal = "kitty"
local fileManager = "dolphin"
local editor = "code"

local d = "[Temporal]"
local temp = "/home/amadeus177153/.config/hypr/scripts/tmp.sh"
local tmp = "/home/amadeus177153/.config/hypr/scripts/temp.sh"
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(temp), { locked = true, description = d .. " abre waybar y demas mamadas" })
-- hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(tmp), { locked = true, description = d .. " abre waybar y demas mamadas" })


-- Funciones auxiliares heredadas del nuevo HyDE
local cycle_fullscreen = function()
    local active_window = assert(hl.get_active_window(), "No active window to toggle fullscreen")
    local current_state = tonumber(active_window.fullscreen) or 0
    local next_state = (current_state + 1) % 3
    hl.dispatch(
        hl.dsp.window.fullscreen_state(
            {
                internal = next_state,
                client = next_state,
                window = active_window
            }
        )
    )
end

local move_window = function(dir, pix)
    local lut = {l = {-1, 0}, r = {1, 0}, u = {0, -1}, d = {0, 1}}
    lut.left, lut.right, lut.up, lut.down = lut.l, lut.r, lut.u, lut.d
    local m = lut[dir]
    return function()
        local args =
            hl.get_active_window().floating and {x = m[1] * pix, y = m[2] * pix, relative = true} or {direction = dir}
        hl.dispatch(hl.dsp.window.move(args))
    end
end

local wm = "Window Management"
local d = "[Window Management]"

hl.bind(mainMod .. " + Q", hl.dsp.window.close(), { locked = true, description = d .. " cerrar ventana enfocada" })
hl.bind("ALT + F4", hl.dsp.window.kill(), { locked = true, description = d .. " matar proceso de la ventana enfocada" })
hl.bind(mainMod .. " + SHIFT + Delete", hl.dsp.exit(), { locked = true, description = d .. " cerrar sesion hyprland" })
-- hl.bind(mainMod .. " + W", hl.dsp.window.float({action = "toggle"}), { locked = true, description = d .. " alternar modo flotante" })

hl.bind(mainMod .. " + W", function()
    hl.dsp.window.float({action = "toggle"})
end, { locked = true, description = d .. " alternar modo flotante" })

hl.bind(mainMod .. " + G", hl.dsp.group.toggle(), { description = d .. " alternar grupo" })
hl.bind("SHIFT + F11", cycle_fullscreen, { locked = true, description = d .. " alternar pantalla completa" })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(hyde.sh.session.lock()), { description = d .. " bloquear pantalla" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd(hyde.sh.window.pin()), { locked = true, description = d .. " fijar ventana enfocada" })
hl.bind(mainMod .. " + Delete", hl.dsp.exec_cmd(hyde.sh.session.logout.launcher()), { locked = true, description = d .. " menu de apagado" })
hl.bind("Alt_R + Control_R", hl.dsp.exec_cmd(hyde.sh.waybar("--hide")), { locked = true, description = d .. " alternar y recargar waybar" })

local d = "[Window Management|Group Navigation]"
hl.bind(mainMod .. " + CONTROL + H", hl.dsp.group.prev(), { locked = true, description = d .. " grupo activo anterior" })
hl.bind(mainMod .. " + CONTROL + L", hl.dsp.group.next(), { locked = true, description = d .. " grupo activo siguiente" })

local d = "[Window Management|Change focus]"
hl.bind(mainMod .. " + Left", hl.dsp.focus({ direction = "left" }), { locked = true, description = d .. " enfocar izquierda" })
hl.bind(mainMod .. " + Right", hl.dsp.focus({ direction = "right" }), { locked = true, description = d .. " enfocar derecha" })
hl.bind(mainMod .. " + Up", hl.dsp.focus({ direction = "up" }), { locked = true, description = d .. " enfocar arriba" })
hl.bind(mainMod .. " + Down", hl.dsp.focus({ direction = "down" }), { locked = true, description = d .. " enfocar abajo" })
hl.bind("ALT + Tab", hl.dsp.exec_cmd(hyde.sh.altab("--next")), { locked = true, description = d .. " ciclar enfoque" })

local d = "[Window Management|Resize Active Window]"
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.window.resize({x = 30, y = 0, relative = true}), { locked = true, repeating = true, description = d .. " redimensionar ventana derecha" })
hl.bind(mainMod .. " + SHIFT + Left", hl.dsp.window.resize({x = -30, y = 0, relative = true}), { locked = true, repeating = true, description = d .. " redimensionar ventana izquierda" })
hl.bind(mainMod .. " + SHIFT + Up", hl.dsp.window.resize({x = 0, y = -30, relative = true}), { locked = true, repeating = true, description = d .. " redimensionar ventana arriba" })
hl.bind(mainMod .. " + SHIFT + Down", hl.dsp.window.resize({x = 0, y = 30, relative = true}), { locked = true, repeating = true, description = d .. " redimensionar ventana abajo" })

local d = "[Window Management|Move active window across workspace]"
hl.bind(mainMod .. " + SHIFT + CONTROL + left", move_window("l", 30), { locked = true, repeating = true, description = d .. " mover ventana activa izquierda" })
hl.bind(mainMod .. " + SHIFT + CONTROL + right", move_window("r", 30), { locked = true, repeating = true, description = d .. " mover ventana activa derecha" })
hl.bind(mainMod .. " + SHIFT + CONTROL + up", move_window("u", 30), { locked = true, repeating = true, description = d .. " mover ventana activa arriba" })
hl.bind(mainMod .. " + SHIFT + CONTROL + down", move_window("d", 30), { locked = true, repeating = true, description = d .. " mover ventana activa abajo" })

local d = "[Window Management|Move & Resize with mouse]"
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { locked = true, mouse = true, description = d .. " mantener para mover ventana" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { locked = true, mouse = true, description = d .. " mantener para redimensionar ventana" })
hl.bind(mainMod .. " + Z", hl.dsp.window.drag(), { locked = true, mouse = true, description = d .. " mantener para mover ventana" })
hl.bind(mainMod .. " + X", hl.dsp.window.resize(), { locked = true, mouse = true, description = d .. " mantener para redimensionar ventana" })

local d = "[Window Management]"
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"), { description = d .. " alternar division" })

local l = "Launcher"
local d = "[Launcher|Apps]"
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal), { locked = true, description = d .. " emulador de terminal" })
hl.bind(mainMod .. " + ALT + T", hl.dsp.exec_cmd("hyde-shell pypr toggle console"), { locked = true, description = d .. " terminal desplegable" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager), { description = d .. " explorador de archivos" })
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(editor), {  description = d .. " editor de texto" })
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(BROWSER), { description = d .. " navegador web" })
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("firefox --private-window"), { locked = true, description = d .. " navegador web incognito" })
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"webcord\" ; then hyprctl dispatch killactive \"\" ; else " .. DISCORD .. "; fi'"), { locked = true, description = d .. " discord" })
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("flatpak kill io.github.spacingbat3.webcord"), { locked = true, description = d .. " cerrar discord" })
hl.bind(mainMod .. " + CONTROL + S", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j | jq -r .class | grep -iq steam ; then hyprctl dispatch killactive; else steam; fi'"), { locked = true, description = d .. " steam" })
hl.bind(mainMod .. " + CONTROL + S", hl.dsp.exec_cmd("sh -c 'hyprctl activewindow | grep -iq steam && hyprctl dispatch killactive || steam'"), { locked = true, description = d .. " steam" })
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("hyde-shell system.monitor.sh"), { locked = true, description = d .. " monitor del sistema" })
hl.bind(mainMod .. " + ALT + Escape", hl.dsp.exec_cmd(terminal .. " -e btop"), { locked = true, description = d .. " abrir btop" })
hl.bind(mainMod .. " + SHIFT + Escape", hl.dsp.exec_cmd(terminal .. " -e nvtop"), { locked = true, description = d .. " abrir nvtop" })

local d = "[Launcher|Rofi menus]"
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(hyde.sh.menu.apps()), { locked = true, description = d .. " buscador de aplicaciones" })
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd(hyde.sh.menu.windows()), { locked = true, description = d .. " intercambiador de ventanas" })
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd(hyde.sh.menu.files()), { locked = true, description = d .. " buscador de archivos" })
hl.bind(mainMod .. " + minus", hl.dsp.exec_cmd(hyde.sh.menu.binds()), { locked = true, description = d .. " pista de atajos" })
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd(hyde.sh.menu.emoji()), { locked = true, description = d .. " selector de emojis" })
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd(hyde.sh.menu.glyph()), { locked = true, description = d .. " selector de glifos" })
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(hyde.sh.menu.clipboard()), { locked = true, description = d .. " portapapeles" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(hyde.sh.menu.cliphist()), { locked = true, description = d .. " administrador del portapapeles" })
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd(hyde.sh.menu.launcher()), { locked = true, description = d .. " seleccionar lanzador rofi" })

local hc = "Hardware Controls"
local d = "[Hardware Controls|Audio]"
hl.bind("F10", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-o", "m")), { locked = true, description = d .. " alternar silencio de salida" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-o", "m")), { locked = true, description = d .. " alternar silencio de salida" })
hl.bind("F11", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-o", "d")), { locked = true, repeating = true, description = d .. " bajar volumen" })
hl.bind("F12", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-o", "i")), { locked = true, repeating = true, description = d .. " subir volumen" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-i", "m")), { locked = true, description = d .. " alternar silencio de microfono" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-o", "d")), { locked = true, repeating = true, description = d .. " bajar volumen" })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(hyde.sh.volumecontrol("-o", "i")), { locked = true, repeating = true, description = d .. " subir volumen" })

local d = "[Hardware Controls|Media]"
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = d .. " reproducir o pausar multimedia" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true, description = d .. " pausar multimedia" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = d .. " multimedia siguiente" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true, description = d .. " multimedia anterior" })
hl.bind(mainMod .. " + CONTROL + M", hl.dsp.exec_cmd(hyde.sh.window.mute()), { locked = true, description = d .. " alternar silencio en ventana activa" })

local d = "[Hardware Controls|Brightness]"
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(hyde.sh.brightnesscontrol("-i")), { locked = true, repeating = true, description = d .. " subir brillo" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(hyde.sh.brightnesscontrol("-d")), { locked = true, repeating = true, description = d .. " bajar brillo" })

local ut = "Utilities"
local d = "[Utilities]"
-- hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(hyde.sh.kb.switch()), { locked = true, description = d .. " cambiar distribucion de teclado" })
hl.bind(mainMod .. " + ALT + G", hl.dsp.exec_cmd(hyde.sh.gamemode()), { locked = true, description = d .. " modo juego" })
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("hyde-shell gamelauncher"), { locked = true, description = d .. " abrir lanzador de juegos" })

local d = "[Utilities|Screen Capture]"
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -an"), { locked = true, description = d .. " selector de color" })
hl.bind(mainMod .. " + CONTROL + P", hl.dsp.exec_cmd(hyde.sh.screenshot.freeze()), { locked = true, description = d .. " congelar y recortar pantalla" })
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("sh -c 'ARCHIVO=\"/tmp/Captura_$(date +%H-%M-%S).png\" ; grim -g \"$(slurp)\" \"$ARCHIVO\" && echo -n \"file://$ARCHIVO\"| wl-copy -t text/uri-list'"), { locked = true, description = d .. " recortar pantalla" })
hl.bind(mainMod .. " + ALT + P", hl.dsp.exec_cmd(hyde.sh.screenshot.monitor()), { locked = true, description = d .. " capturar monitor" })
hl.bind("Print", hl.dsp.exec_cmd(hyde.sh.screenshot.full()), { locked = true, description = d .. " capturar todos los monitores" })

local rice = "Theming and Wallpaper"
local d = "[Theming and Wallpaper]"
hl.bind(mainMod .. " + ALT + Right", hl.dsp.exec_cmd(hyde.sh.wallpaper("--next")), { locked = true, description = d .. " siguiente fondo global" })
hl.bind(mainMod .. " + ALT + Left", hl.dsp.exec_cmd(hyde.sh.wallpaper("--prev")), { locked = true, description = d .. " anterior fondo global" })
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(hyde.sh.menu.wallpapers()), { locked = true, description = d .. " seleccionar fondo global" })
hl.bind(mainMod .. " + ALT + Up", hl.dsp.exec_cmd("hyde-shell waybar --next"), { locked = true, description = d .. " siguiente diseño waybar" })
hl.bind(mainMod .. " + ALT + Down", hl.dsp.exec_cmd("hyde-shell waybar --prev"), { locked = true, description = d .. " anterior diseño waybar" })
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd(hyde.sh.menu.wallbash()), { locked = true, description = d .. " selector de modo wallbash" })
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd(hyde.sh.menu.themes()), { locked = true, description = d .. " seleccionar tema" })
hl.bind(mainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("hyde-shell animations --select"), { locked = true, description = d .. " seleccionar animaciones" })
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.exec_cmd("hyde-shell hyprlock --select"), { locked = true, description = d .. " seleccionar diseño hyprlock" })

local ws = "Workspaces"
local d = "[Workspaces|Navigation]"
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i, hl.dsp.focus({ workspace = i }), { locked = true, description = d .. " navegar al espacio " .. i })
end
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }), { locked = true, description = d .. " navegar al espacio 10" })

local d = "[Workspaces|Navigation|Relative workspace]"
hl.bind(mainMod .. " + CONTROL + Right", hl.dsp.focus({ workspace = "r+1" }), { description = d .. " espacio activo siguiente" })
hl.bind(mainMod .. " + CONTROL + Left", hl.dsp.focus({ workspace = "r-1" }), { description = d .. " espacio activo anterior" })

local d = "[Workspaces|Navigation]"
hl.bind(mainMod .. " + CONTROL + Down", hl.dsp.focus({ workspace = "empty" }), { locked = true, description = d .. " navegar al espacio vacio mas cercano" })

local d = "[Workspaces|Move window to workspace]"
for i = 1, 9 do
    hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }), { locked = true, description = d .. " mover al espacio " .. i })
end
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }), { locked = true, description = d .. " mover al espacio 10" })

local d = "[Workspaces|Move window to workspace|Relative workspace]"
hl.bind(mainMod .. " + CONTROL + ALT + Right", hl.dsp.window.move({ workspace = "r+1" }), { locked = true, description = d .. " mover ventana al espacio relativo siguiente" })
hl.bind(mainMod .. " + CONTROL + ALT + Left", hl.dsp.window.move({ workspace = "r-1" }), { locked = true, description = d .. " mover ventana al espacio relativo anterior" })

local d = "[Workspaces|Navigation|Mouse]"
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { locked = true, description = d .. " espacio siguiente" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { locked = true, description = d .. " espacio anterior" })

local d = "[Workspaces|Navigation|Special workspace]"
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special" }), { locked = true, description = d .. " mover al scratchpad" })
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special(), { description = d .. " alternar scratchpad" })

local d = "[Workspaces|Move window (Don't follow)]"
for i = 1, 9 do
    hl.bind(mainMod .. " + ALT + " .. i, hl.dsp.window.move({ workspace = i, follow = false }), { locked = true, description = d .. " mover al espacio " .. i .. " (silencioso)" })
end
hl.bind(mainMod .. " + ALT + 0", hl.dsp.window.move({ workspace = 10, follow = false }), { locked = true, description = d .. " mover al espacio 10 (silencioso)" })