-- Generated by nwg-displays on 2026-05-19 at 16:57:16. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@240.3",
    position = "1920x0",
    scale = 1.0
})
