-- Generated by nwg-displays on 2026-07-31 at 19:27:22. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    disabled = true
})
hl.monitor({
    output = "FALLBACK",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
