-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █▄░█ █░█ █ █▀▄ █ ▄▀█

-- █░▀█ ▀▄▀ █ █▄▀ █ █▀█

-- Optimizador: Hyprland + NVIDIA Open 610+ @ 100Hz

-- -----------------------------------------------------------------

-- Variables Core del Ecosistema NVIDIA

-- -----------------------------------------------------------------

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("GBM_BACKEND", "nvidia-drm")

-- Aceleración de Video por Hardware (Obligatorio para RTX 3060)

-- Descarga el procesamiento de video del Ryzen 5 a los tensores de la GPU.

hl.env("NVD_BACKEND", "direct")

-- -----------------------------------------------------------------

-- Integración Estricta con Wayland (Prevención de XWayland Stuttering)

-- -----------------------------------------------------------------

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

hl.env("OZONE_PLATFORM", "wayland")

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- -----------------------------------------------------------------

-- Persistencia de Caché de Sombreadores (Overwatch / DXVK / Vulkan)

-- -----------------------------------------------------------------

hl.env("__GL_SHADER_DISK_CACHE_PATH", "~/.cache/nvidia/glcache")

hl.env("__GL_SHADER_DISK_CACHE_SIZE", 53687091200)

hl.env("__GL_SHADER_DISK_CACHE_SKIP_CLEANUP", 1)

hl.env("DXVK_STATE_CACHE_PATH", "~/.cache/nvidia/dxvk")

hl.env("VK_ICD_FILENAMES", "/usr/share/vulkan/icd.d/nvidia_icd.json")

-- -----------------------------------------------------------------

-- Renderizado y Mitigación de Desincronización (Flickering)

-- -----------------------------------------------------------------

-- Los cursores por hardware aún pueden presentar anomalías en transiciones rápidas.

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

