-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See hyprsunset documentation: https://wiki.hypr.land/Hypr-Ecosystem/hyprsunset/

-- # Max-gamma sets the upper limit for color adjustments

-- max-gamma = 150

-- Day profile: Returns screen to native colors

hl.config({
    profile = {
        -- time = 06:00
        -- identity = true
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output

-- Night Profile: Applies a cooler white filter with reduced intensity

hl.config({
    profile = {
        -- time = 21:00
        -- temperature = 5500
        -- gamma = 0.8
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output
