-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Configuring hypridle

-- See: https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

-- 

-- hypridle.conf - Hypridle configuration for HyDE

-- Handles idle actions: dim, lock, DPMS, suspend, and custom listeners

-- 

-- Listeners: Each listener block defines an idle timeout and actions to run

-- 

-- For more info, see: https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

--!      ░▒▒▒░░░▓▓           ___________

--!    ░░▒▒▒░░░░░▓▓        //___________/

--!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____

--!   ░░▒▒░░░░░▓▓▓▓▓ | | | | |  | |  __/

--!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___

--!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/

--!       ░▒▓▓   ▓▓  //____/

local LOCK_CMD = "hyde-shell lockscreen.sh"

-- Calls $LOCKSCREEN default is hyprlock

local UNLOCK_CMD = "sh -c 'sleep 3 && pkill -9 $(hyde-shell lockscreen --get)'"

-- kills the lockscreen after 3 seconds for cleanup

hl.config({
    general = {
        lock_cmd = "hyde-shell lockscreen.sh",
        -- command when `loginctl lock-session` is called
        unlock_cmd = "sh -c 'sleep 3 && pkill -9 $(hyde-shell lockscreen --get)'",
        -- command when `loginctl unlock-session` is called
        ignore_dbus_inhibit = false,
        -- Ignore dbus idle-inhibit requests (false = respect them)
        ignore_systemd_inhibit = false,
        -- Ignore systemd-inhibit --what=idle (false = respect them)
        -- before_sleep_cmd =     # command ran before sleep
        -- after_sleep_cmd = # notify-send "Awake!"  # command ran after sleep
    },
})

-- // --- Listener: Dim display after 60s idle ---

hl.config({
    listener = {
        timeout = 60,
        on_timeout = "brightnessctl -s && brightnessctl s 1%",
        -- Save and set brightness to 1%
        on_resume = "brightnessctl -r",
        -- Restore brightness on activity
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- // --- Listener: Lock after 120s idle ---

-- Locks the session before DPMS off, so the screen is not visible after wake

hl.config({
    listener = {
        timeout = 120,
        on_timeout = "loginctl lock-session",
        -- Try system lock, fallback to $LOCKSCREEN
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- // --- Listener: DPMS off after 300s idle ---

-- Turns off display (but not if media is playing)

hl.config({
    listener = {
        timeout = 300,
        on_timeout = "hyprctl dispatch dpms off",
        -- Turn off display
        on_resume = "hyprctl dispatch dpms on",
        -- Turn display back on
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- // --- Listener: Suspend after 500s idle ---

hl.config({
    listener = {
        timeout = 500,
        on_timeout = "systemctl suspend",
        -- Suspend system
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- // --- Custom listeners ---

-- hyprlang noerror true

-- Source any additional listener configs from this path (wildcard supported)

-- Note: 'source' command is not implemented yet in hyprlang, but left for future use

-- source = ./hypridle/* -> requires manual conversion
-- local _ = require("_.hypridle._")
-- TODO: convert ./hypridle/* to .lua and use require()

-- hyprlang noerror false
