-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local HYDE_HYPRLAND = "set"

--! Do not remove - HyDE marker to prevent file overwrite

--* You can freely edit this file, but make sure to not remove the above line!

--* All Files Below are yours to modify!

--!      ░▒▒▒░░░▓▓           ___________

--!    ░░▒▒▒░░░░░▓▓        //___________/

--!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____

--!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/

--!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___

--!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/

--!       ░▒▓▓   ▓▓  //____/

-- ------------------------------------------------------

--TODO Please remove this block if you are sure $HYPRLAND_CONFIG is set

--? This is only use for fallback

-- source = $HOME/.local/share/hyde/hyprland.conf -> requires manual conversion
-- local hyprland = require("_local.share.hyde.hyprland")
-- TODO: convert $HOME/.local/share/hyde/hyprland.conf to .lua and use require()

-- Fallback when HYPRLAND_CONFIG is not set

-- -------------------------------------------------------

--? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

-- source = ./keybindings.conf -> requires manual conversion
-- local keybindings = require("_.keybindings")
-- TODO: convert ./keybindings.conf to .lua and use require()

-- Keyboard shortcuts

-- source = ./windowrules.conf -> requires manual conversion
-- local windowrules = require("_.windowrules")
-- TODO: convert ./windowrules.conf to .lua and use require()

-- Window rules

-- source = ./monitors.conf -> requires manual conversion
-- local monitors = require("_.monitors")
-- TODO: convert ./monitors.conf to .lua and use require()

-- Monitor configuration

-- source = ./userprefs.conf -> requires manual conversion
-- local userprefs = require("_.userprefs")
-- TODO: convert ./userprefs.conf to .lua and use require()

-- Your hyprland configuration // Edit this file to change your Hyprland configuration

hl.config({
    input = {
        kb_layout = "latam",
    },
})
