-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀

--# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

-- mira https://wiki.hypr.land/configuring/keywords/ para más información

-- para ver ejemplos de atajos, mira https://wiki.hypr.land/configuring/binds/

--? ------- COMPATIBLE CON KEYBINDS_HYPRLAND_V_0_53 ----------------

--   Esta configuración es compatible con los cambios de atajos en Hyprland v0.53+

--   Para asegurar que tu sistema funcione, no deshabilitaremos este bloque

--   Los archivos de plantilla del usuario se proporcionarán en $XDG_DATA_HOME/hyde/templates/hypr/keybindings.conf para actualización manual.

--? ------- Agrupación de atajos para una gestión más fácil ----------------

--  $d=[Nombre del Grupo|Nombre del Subgrupo1|Nombre del Subgrupo2|...]

-- '$d' es una variable que se utiliza para agrupar atajos (o usar otra variable)

-- Esto es solo para fines de organización y no es una variable definida por hyprland

-- Lo que hicimos aquí fue modificar la Descripción de los atajos para incluir el nombre del grupo

-- El $d será analizado como una clave separada para usarse en una GUI (interfaz gráfica) o algo visual

-- [Principal|Subgrupo1|Subgrupo2|...]

-- Principal - El nombre del grupo principal

-- Subgrupo1.. - Los nombres de los subgrupos se pueden usar para evitar repetir la misma descripción

--? ------- Variables ----------------

-- Por defecto si está comentado

-- $mainMod = Super # tecla super / meta / windows

-- Asignar aplicaciones

-- $TERMINAL = kitty

-- $EDITOR = code

-- $EXPLORER = dolphin

local BROWSER = "firefox"

-- $KILLACTIVE = hyprctl dispatch killactive ""

local DISCORD = "flatpak run io.github.spacingbat3.webcord"

local wm = "Window Management"

local d = "[Window Management]"

-- Cierra la ventana que tienes actualmente enfocada.

hl.bind("$mainMod" .. " + " .. "Q", hl.dsp.exec_cmd("$KILLACTIVE"))

-- Atajo alternativo (clásico de Windows) para cerrar la ventana enfocada.

hl.bind("Alt" .. " + " .. "F4", hl.dsp.exec_cmd("$KILLACTIVE"))

-- Cierra tu sesión actual de Hyprland (regresa al login).

hl.bind("$mainMod + Shift" .. " + " .. "Delete", hl.dsp.exec_cmd("hyde-shell logout"))

-- Cambia la ventana enfocada entre el modo "flotante" y el modo "mosaico" (tiling).

hl.bind("$mainMod" .. " + " .. "W", hl.dsp.window.float())

-- Agrupa o desagrupa ventanas para manejarlas por pestañas (tabbed).

hl.bind("$mainMod" .. " + " .. "G", hl.dsp.group.toggle())

-- Pone la ventana enfocada en modo pantalla completa.

hl.bind("Shift" .. " + " .. "F11", hl.dsp.window.fullscreen())

-- Bloquea la pantalla de tu computadora.

hl.bind("$mainMod" .. " + " .. "L", hl.dsp.exec_cmd("hyde-shell lock-session"))

-- Fija (hace "pin") una ventana flotante para que sea visible en todos los espacios de trabajo.

hl.bind("$mainMod + Shift" .. " + " .. "F", hl.dsp.exec_cmd("hyde-shell window.pin"))

-- Muestra el menú gráfico de apagado, reinicio y cierre de sesión.

hl.bind("$mainMod" .. " + " .. "Delete", hl.dsp.exec_cmd("hyde-shell logoutlaunch"))

-- Oculta temporalmente la barra superior (Waybar) y recarga su configuración.

hl.bind("Alt_R" .. " + " .. "Control_R", hl.dsp.exec_cmd("hyde-shell waybar --hide"))

-- bindd = ALT_R, Control_R, alternar waybar, exec, killall waybar || waybar # alterna waybar sin recargar, esto es más rápido

local d = "[Window Management|Group Navigation]"

-- Navega hacia la ventana anterior dentro de un grupo de ventanas (cuando usas $mainMod + G).

hl.bind("$mainMod + Control" .. " + " .. "H", hl.dsp.group.next({ forward = false }))

-- Navega hacia la ventana siguiente dentro de un grupo de ventanas.

hl.bind("$mainMod + Control" .. " + " .. "L", hl.dsp.group.next())

local d = "[Window Management|Change focus]"

-- Mueve el foco hacia la ventana de la izquierda, derecha, arriba o abajo respectivamente.

hl.bind("$mainMod" .. " + " .. "Left", hl.dsp.focus({ direction = "left" }))

hl.bind("$mainMod" .. " + " .. "Right", hl.dsp.focus({ direction = "right" }))

hl.bind("$mainMod" .. " + " .. "Up", hl.dsp.focus({ direction = "up" }))

hl.bind("$mainMod" .. " + " .. "Down", hl.dsp.focus({ direction = "down" }))

-- Cicla el foco entre las ventanas abiertas, similar al Alt+Tab clásico, trayendo la seleccionada al frente.

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.exec_cmd("hyprctl --batch \"dispatch cyclenext ; dispatch alterzorder top\""))

local d = "[Window Management|Resize Active Window]"

-- Redimensiona la ventana enfocada hacia la derecha, izquierda, arriba o abajo respectivamente.

hl.bind("$mainMod + Shift + Right", hl.dsp.resizeactive("30 0"))
hl.bind("$mainMod + Shift + Left", hl.dsp.resizeactive("-30 0"))
hl.bind("$mainMod + Shift + Up", hl.dsp.resizeactive("0 -30"))
hl.bind("$mainMod + Shift + Down", hl.dsp.resizeactive("0 30"))

-- Mueve la ventana activa por el espacio de trabajo actual con mainMod + Shift + Control [←→↑↓]

local d = "[Window Management|Move active window across workspace]"

local moveactivewindow = "grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive"

-- Mueve de lugar la ventana enfocada hacia la izquierda, derecha, arriba o abajo dentro de tu espacio de trabajo.

hl.bind("$mainMod + Shift + Control" .. " + " .. "left", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive -30 0 || hyprctl dispatch movewindow l"))

hl.bind("$mainMod + Shift + Control" .. " + " .. "right", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 30 0 || hyprctl dispatch movewindow r"))

hl.bind("$mainMod + Shift + Control" .. " + " .. "up", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 -30 || hyprctl dispatch movewindow u"))

hl.bind("$mainMod + Shift + Control" .. " + " .. "down", hl.dsp.exec_cmd("grep -q true <<< $(hyprctl activewindow -j| jq -r.floating) && hyprctl dispatch moveactive 0 30 || hyprctl dispatch movewindow d"))

-- Mover/Redimensionar ventana enfocada

local d = "[Window Management|Move & Resize with mouse]"

-- Mantén presionada la tecla Modificadora (Super/Windows) y el Clic Izquierdo para arrastrar/mover la ventana con el ratón.

hl.bind("$mainMod" .. " + " .. "mouse:272", nil, { mouse = true })

-- Mantén presionada la tecla Modificadora y el Clic Derecho para redimensionar la ventana con el ratón.

hl.bind("$mainMod" .. " + " .. "mouse:273", hl.dsp.window.resize(nil), { mouse = true })

-- Alternativas con teclado: mantén Modificadora + Z para mover con el ratón, o Modificadora + X para redimensionar con el ratón.

hl.bind("$mainMod" .. " + " .. "Z", nil, { mouse = true })

hl.bind("$mainMod" .. " + " .. "X", hl.dsp.window.resize(nil), { mouse = true })

-- Alternar la división de la ventana enfocada

local d = "[Window Management]"

-- Cambia la dirección en la que se divide la siguiente ventana (horizontal vs vertical).

hl.bind("$mainMod" .. " + " .. "J", hl.dsp.layout("togglesplit"))

local l = "Launcher"

local d = "[Launcher|Apps]"

-- Lanza tu terminal por defecto.

hl.bind("$mainMod" .. " + " .. "T", hl.dsp.exec_cmd("$TERMINAL"))

-- Abre una terminal desplegable (estilo "Quake") en la parte superior o inferior.

hl.bind("$mainMod + Alt" .. " + " .. "T", hl.dsp.exec_cmd("hyde-shell pypr toggle console"))

-- Lanza el explorador de archivos.

hl.bind("$mainMod" .. " + " .. "E", hl.dsp.exec_cmd("$EXPLORER"))

-- Lanza el editor de texto/código.

hl.bind("$mainMod" .. " + " .. "C", hl.dsp.exec_cmd("$EDITOR"))

-- Lanza el navegador web.

hl.bind("$mainMod" .. " + " .. "B", hl.dsp.exec_cmd("firefox"))

-- Lanza el navegador web.

hl.bind("$mainMod + Shift" .. " + " .. "B", hl.dsp.exec_cmd("firefox --private-window"))

-- Lanza discord (webcord) o cierra la ventana si ya está en foco

hl.bind("$mainMod" .. " + " .. "D", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"webcord\" ; then hyprctl dispatch killactive \"\" ; else flatpak run io.github.spacingbat3.webcord; fi'"))

-- Mata el proceso de discord por completo (cierra la aplicación de raíz)

hl.bind("$mainMod + Shift" .. " + " .. "D", hl.dsp.exec_cmd("flatpak kill io.github.spacingbat3.webcord"))

-- Lanza Steam o cierra la ventana

hl.bind("$mainMod + Control_L" .. " + " .. "S", hl.dsp.exec_cmd("bash -c 'if hyprctl activewindow -j| jq -r.class| grep -iq \"steam\" ; then hyprctl dispatch killactive \"\" ; else steam; fi'"))

-- Mata el proceso de steam por completo

hl.bind("$mainMod + Shift + Control_L" .. " + " .. "S", hl.dsp.exec_cmd("pkill -9 -f steam"))

-- Lanza el monitor del sistema (administrador de tareas).

hl.bind("$mainMod" .. " + " .. "Escape", hl.dsp.exec_cmd("hyde-shell system.monitor"))

-- Lanza el monitor btop.

hl.bind("$mainMod + Alt" .. " + " .. "Escape", hl.dsp.exec_cmd("$TERMINAL -e btop"))

-- Lanza el monitor nvtop.

hl.bind("$mainMod + Shift" .. " + " .. "Escape", hl.dsp.exec_cmd("$TERMINAL -e nvtop"))

local d = "[Launcher|Rofi menus]"

local rofi-launch = "hyde-shell rofilaunch"

-- Lanza el menú principal de búsqueda de aplicaciones (Rofi).

hl.bind("$mainMod" .. " + " .. "A", hl.dsp.exec_cmd("pkill -x rofi || $rofi-launch d"))

-- Lanza el selector para cambiar entre ventanas que ya tienes abiertas.

hl.bind("$mainMod" .. " + " .. "TAB", hl.dsp.exec_cmd("pkill -x rofi || $rofi-launch w"))

-- Abre un buscador de archivos integrado en Rofi.

hl.bind("$mainMod + Shift" .. " + " .. "E", hl.dsp.exec_cmd("pkill -x rofi || $rofi-launch f"))

-- Muestra una hoja de cheat/ayuda con todos los atajos de teclado.

hl.bind("$mainMod" .. " + " .. "minus", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell keybinds_hint c"))

-- Abre un selector para copiar Emojis al portapapeles.

hl.bind("$mainMod" .. " + " .. "comma", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell emoji-picker"))

-- Abre un selector de caracteres especiales y glifos.

hl.bind("$mainMod" .. " + " .. "period", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell glyph-picker"))

-- Abre el historial de tu portapapeles para pegar cosas que copiaste antes.

hl.bind("$mainMod" .. " + " .. "V", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell cliphist -c"))

-- Abre el administrador completo del portapapeles.

hl.bind("$mainMod + Shift" .. " + " .. "V", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell cliphist"))

-- Abre un menú para cambiar el estilo visual de los menús Rofi.

hl.bind("$mainMod + Shift" .. " + " .. "A", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell rofiselect"))

local hc = "Hardware Controls"

local d = "[Hardware Controls|Audio]"

-- Activa o desactiva el sonido general (Mute).

hl.bind("F10", hl.dsp.exec_cmd("hyde-shell volumecontrol -o m"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("hyde-shell volumecontrol -o m"), { locked = true })

-- Baja el volumen general.

hl.bind("F11", hl.dsp.exec_cmd("hyde-shell volumecontrol -o d"), { locked = true })

-- Sube el volumen general.

hl.bind("F12", hl.dsp.exec_cmd("hyde-shell volumecontrol -o i"), { locked = true })

-- Activa o desactiva el micrófono (Mute).

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("hyde-shell volumecontrol -i m"), { locked = true })

-- Controles de volumen y brillo usando las teclas multimedia dedicadas del teclado.

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("hyde-shell volumecontrol -o d"), { locked = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("hyde-shell volumecontrol -o i"), { locked = true })

local d = "[Hardware Controls|Media]"

-- Reproduce o pausa la música / video actual.

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

-- Salta a la siguiente pista.

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

-- Regresa a la pista anterior.

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Silencia únicamente el audio de la ventana que estás usando actualmente (útil para callar navegadores o juegos).

hl.bind("$mainMod + Control" .. " + " .. "M", hl.dsp.exec_cmd("hyde-shell window.mute"))

local d = "[Hardware Controls|Brightness]"

-- Aumenta el brillo de la pantalla.

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("hyde-shell brightnesscontrol i"), { locked = true })

-- Disminuye el brillo de la pantalla.

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("hyde-shell brightnesscontrol d"), { locked = true })

local ut = "Utilities"

local d = "[Utilities]"

-- Cambia la distribución/idioma del teclado.

hl.bind("$mainMod" .. " + " .. "K", hl.dsp.exec_cmd("hyde-shell keyboardswitch"), { locked = true })

-- Activa el "Modo Juego" (desactiva animaciones y decoraciones para mejorar rendimiento mientras juegas).

hl.bind("$mainMod + Alt" .. " + " .. "G", hl.dsp.exec_cmd("hyde-shell gamemode"))

-- Lanza un menú optimizado para abrir juegos de Steam, Lutris, etc.

hl.bind("$mainMod + Shift" .. " + " .. "G", hl.dsp.exec_cmd("hyde-shell gamelauncher"))

local d = "[Utilities|Screen Capture]"

-- Selector de color: te permite hacer clic en cualquier lugar de la pantalla para copiar el código de color HEX.

hl.bind("$mainMod + Shift" .. " + " .. "P", hl.dsp.exec_cmd("hyprpicker -an"))

-- Herramienta de recortes: seleccionas un área para tomarle captura de pantalla.

hl.bind("$mainMod + Control" .. " + " .. "P", hl.dsp.exec_cmd("hyde-shell screenshot s"))

-- lo mimo pero temporal

hl.bind("$mainMod" .. " + " .. "P", hl.dsp.exec_cmd("sh -c 'ARCHIVO=\"/tmp/Captura_$(date +%H-%M-%S).png\" ; grim -g \"$(slurp)\" \"$ARCHIVO\" && echo -n \"file://$ARCHIVO\"| wl-copy -t text/uri-list'"))

-- Toma una captura de todo el monitor actual donde está tu ratón.

hl.bind("$mainMod + Alt" .. " + " .. "P", hl.dsp.exec_cmd("hyde-shell screenshot m"), { locked = true })

-- Toma una captura de todos tus monitores al mismo tiempo.

hl.bind("Print", hl.dsp.exec_cmd("hyde-shell screenshot p"), { locked = true })

-- TODO Hacer un menú rofi principal para estos selectores

local rice = "Theming and Wallpaper"

local d = "[Theming and Wallpaper]"

-- Cambia al fondo de pantalla global siguiente o anterior de tu carpeta/sistema.

hl.bind("$mainMod + Alt" .. " + " .. "Right", hl.dsp.exec_cmd("hyde-shell wallpaper -Gn"))

hl.bind("$mainMod + Alt" .. " + " .. "Left", hl.dsp.exec_cmd("hyde-shell wallpaper -Gp"))

-- Abre un menú para que selecciones manualmente el fondo de pantalla que quieres.

hl.bind("$mainMod + Shift" .. " + " .. "W", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell wallpaper -SG"))

-- Cambia al estilo/diseño siguiente o anterior de la barra superior de Waybar.

hl.bind("$mainMod + Alt" .. " + " .. "Up", hl.dsp.exec_cmd("hyde-shell wbarconfgen n"))

hl.bind("$mainMod + Alt" .. " + " .. "Down", hl.dsp.exec_cmd("hyde-shell wbarconfgen p"))

-- Abre el selector de 'Wallbash' para generar colores de la interfaz a partir del fondo de pantalla.

hl.bind("$mainMod + Shift" .. " + " .. "R", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell wallbashtoggle -m"))

-- Abre el selector para cambiar el tema visual general.

hl.bind("$mainMod + Shift" .. " + " .. "T", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell themeselect"))

-- Abre un menú para cambiar los estilos de animaciones de las ventanas.

hl.bind("$mainMod+Shift" .. " + " .. "Y", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell animations --select"))

-- Abre el selector para elegir cómo se ve tu pantalla de bloqueo.

hl.bind("$mainMod+Shift" .. " + " .. "U", hl.dsp.exec_cmd("pkill -x rofi || hyde-shell hyprlock --select"))

local ws = "Workspaces"

local d = "[Workspaces|Navigation]"

-- Te lleva directamente a los espacios de trabajo del 1 al 10.

hl.bind("$mainMod" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind("$mainMod" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind("$mainMod" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind("$mainMod" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind("$mainMod" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind("$mainMod" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind("$mainMod" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind("$mainMod" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind("$mainMod" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind("$mainMod" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

local d = "[Workspaces|Navigation|Relative workspace]"

-- Te mueve al espacio de trabajo siguiente o anterior basado en los que están activos.

hl.bind("$mainMod + Control" .. " + " .. "Right", hl.dsp.focus({ workspace = "r+1" }))

hl.bind("$mainMod + Control" .. " + " .. "Left", hl.dsp.focus({ workspace = "r-1" }))

local d = "[Workspaces|Navigation]"

-- Te mueve rápidamente al primer espacio de trabajo que esté vacío.

hl.bind("$mainMod + Control" .. " + " .. "Down", hl.dsp.focus({ workspace = "empty" }))

-- Mover la ventana enfocada a un espacio de trabajo

local d = "[Workspaces|Move window to workspace]"

-- Mueve la ventana que estás usando a un espacio de trabajo del 1 al 10 y te lleva a él.

hl.bind("$mainMod + Shift" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind("$mainMod + Shift" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind("$mainMod + Shift" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind("$mainMod + Shift" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind("$mainMod + Shift" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind("$mainMod + Shift" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind("$mainMod + Shift" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind("$mainMod + Shift" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind("$mainMod + Shift" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind("$mainMod + Shift" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Mover la ventana enfocada a un espacio de trabajo relativo

local d = "[Workspaces]"

-- Mueve la ventana actual al espacio de trabajo relativo siguiente/anterior.

hl.bind("$mainMod + Control+Alt" .. " + " .. "Right", hl.dsp.window.move({ direction = "r+1" }))

hl.bind("$mainMod + Control+Alt" .. " + " .. "Left", hl.dsp.window.move({ direction = "r-1" }))

-- Desplazarse por los espacios de trabajo existentes

local d = "[Workspaces|Navigation]"

-- Te permite cambiar de espacio de trabajo girando la rueda del ratón hacia arriba o abajo mientras presionas Modificadora.

hl.bind("$mainMod" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("$mainMod" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Mover/Cambiar al espacio de trabajo especial (scratchpad)

local d = "[Workspaces|Navigation|Special workspace]"

-- Mueve la ventana actual al "Scratchpad" (un espacio de trabajo oculto) y la oculta.

hl.bind("$mainMod + Shift" .. " + " .. "S", hl.dsp.window.move({ workspace = "special" }))

-- Mueve la ventana al Scratchpad de forma silenciosa (no te saca de tu vista actual).

hl.bind("$mainMod + Alt" .. " + " .. "S", hl.dsp.window.move({ workspace = "special" }, { follow = false }))

-- Muestra u oculta todas las ventanas que enviaste al Scratchpad.

hl.bind("$mainMod" .. " + " .. "S", hl.dsp.workspace.toggle_special(nil))

-- Mover la ventana enfocada a un espacio de trabajo silenciosamente

local d = "[Workspaces|Navigation|Move window silently]"

-- Mueve la ventana actual a un espacio del 1 al 10 PERO te deja en el espacio donde estás (modo silencioso).

hl.bind("$mainMod + Alt" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind("$mainMod + Alt" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }, { follow = false }))

local d = ""

--! desestablecer el nombre del grupo
