-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Generated by nwg-displays on 2026-08-02 at 15:10:11. Do not edit manually.

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@100.0",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@240.3",
    position = "1920x0",
    scale    = 1.0,
})
