-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--! █░█░█ █▀█ █▀█ █▄▀ █▀▀ █░░ █▀█ █░█░█ █▀

--! ▀▄▀▄▀ █▄█ █▀▄ █░█ █▀░ █▄▄ █▄█ ▀▄▀▄▀ ▄█

-- This file sets the current workflow for Hyprland

-- HyDE Controlled content // DO NOT EDIT

-- Edit or add workflows in the ./workflows/ directory

-- and run the 'workflows.sh select' command to update this file

--  Workflows are a set of configurations that can be applied to Hyprland

--   that suits the actual workflow you are doing. 

-- It can be gaming mode, work mode, or anything else you can think of.

-- you can also exec a command within the workflow

local WORKFLOW = "default"

local WORKFLOW_ICON = ""

local WORKFLOW_DESCRIPTION = "Default HyDE configuration// Disables workflow overrides"

local WORKFLOWS_PATH = "./workflows/default.conf"

-- source = $WORKFLOWS_PATH -> requires manual conversion
-- local _WORKFLOWS_PATH = require("_WORKFLOWS_PATH")
-- TODO: convert $WORKFLOWS_PATH to .lua and use require()
